sudo: required
language: ruby
rvm:
  - 2.5
addons:
  firefox: latest
git:
  depth: 1
branches:
  except:
    - gh-pages
script:
  - bundle exec jekyll build
  - bundle exec rake wax:test
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec rake wax:push gh-pages; fi
