title:        'Style Revolution'
description:  'Journal des Dames et des Modes'
url:          'https://stylerevolution.github.io'

# build settings
theme:        minima
permalink:    pretty
exclude:      [Gemfile*, vendor, Rakefile, README*, spec]

# collection settings
collections:
  pages:
    output: true
  exhibits:
    output: true
  plates:
    output: true
    layout: 'plate-page'
    metadata:
      source: 'plates.csv'
    images:
      source: 'preservation_images/plates'

# search index settings
lunr_index:
  - file: 'js/lunr-index.json'
    collections:
      exhibits:
        fields: [title, author]
        content: true
      plates:
        fields: [title, _date, caption, translation, keywords, pid]


# advanced: search tests
quoll:
  - page: '/search/'
    terms: ['turban', 'cheveux', 'crêpe', 'rose']

# js dependencies
js:
  jquery:
    version: 3.2.1
    src: https://code.jquery.com/jquery-3.2.1.min.js
  elasticlunr:
    version: 0.9.6
    src: https://cdnjs.cloudflare.com/ajax/libs/elasticlunr/0.9.6/elasticlunr.min.js
  leaflet:
    version: 1.3.1
    src: https://unpkg.com/leaflet@1.3.1/dist/leaflet.js
  leaflet-iiif:
    version: 2.0.1
    src: https://cdn.jsdelivr.net/npm/leaflet-iiif@2.0.1/leaflet-iiif.min.js


webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
